version: '3'
services:
  next-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
      # Pasamos las variables PÚBLICAS para que se quemen en el build
      args:
        NEXT_PUBLIC_MESA_AYUDA_URL: ${NEXT_PUBLIC_MESA_AYUDA_URL}
        NEXT_PUBLIC_SERVICIOS_ADMIN_URL: ${NEXT_PUBLIC_SERVICIOS_ADMIN_URL}
        NEXT_PUBLIC_SIU_URL: ${NEXT_PUBLIC_SIU_URL}
        NEXT_PUBLIC_SIU2_URL: ${NEXT_PUBLIC_SIU2_URL}

    ports:
      - '3000:3000'

    # Pasamos las variables PRIVADAS (Runtime) como API_URL
    env_file:
      - .env

    # Permite que el contenedor resuelva 'intranet' igual que el host Windows
    extra_hosts:
      - 'intranet:172.16.1.18'
